InquiryApp/Controllers/InquiryController.cs
using BusinessSolution;
using InquiryApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InquiryApp.Controllers;

public class InquiryController : Controller
{
    private readonly InquiryRepository _repo;

    public InquiryController(InquiryRepository repo) => _repo = repo;

    // Display table listing all inquiries in the database
    public IActionResult Index() => View(_repo.GetAllInquiries());


    // Display table with details of a specific inquiry
    public IActionResult ViewInquiry(int id) => View(_repo.GetInquiry(id));


    // Display form for updating an inquiry
    public IActionResult UpdateInquiry(int id) => View(_repo.GetInquiry(id));


    // Update inquiry in the database and display the updated details
    [HttpPost]
    public IActionResult UpdateInquiryToDatabase(InquiryModel inquiry)
    {
        _repo.UpdateInquiry(inquiry);

        return RedirectToAction(nameof(ViewInquiry), new { id = inquiry.Inquiry_ID });
    }

    // Delete selected inquiry and display the updated table with all remaining inquiries
    [HttpPost]
    public IActionResult DeleteInquiry(InquiryModel inquiry)
    {
        _repo.DeleteInquiry(inquiry);

        return RedirectToAction(nameof(Index));
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
}

InquiryApp/Views/Inquiry/Index.cshtml
@using BusinessSolution
@model IEnumerable<InquiryModel>

<!-- Display a table listing all inquiries in the database -->
<h2>Inquiries</h2>
<table class="table">
    <tr>
        <th>Inquiry ID</th>
        <th>Date</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
    </tr>

    @foreach (var inquiry in @Model)
    {
        <tr>
            <td><a href=/Inquiry/ViewInquiry/@inquiry.Inquiry_ID>@inquiry.Inquiry_ID</a></td>
            <td>@inquiry.Date.ToString("MM/dd/yyyy")</td>
            <td>@inquiry.Name</td>
            <td>@inquiry.Phone</td>
            <td>@inquiry.Email</td>
        </tr>
    }
</table>

InquiryApp/Views/Inquiry/UpdateInquiry.cshtml
@using BusinessSolution
@model InquiryModel

<!-- Display form to update an inquiry -->
<h2>Update @Model.Name</h2>

@using (Html.BeginForm("UpdateInquiryToDatabase", "Inquiry", "Post"))
{
    <input asp-for="Inquiry_ID" type="hidden" value="@Model.Inquiry_ID" />
    <input asp-for="Date" type="hidden" value="@Model.Date" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="Phone" class="control-label">Phone</label>
    <input type="text" step="0.01" name="Phone" class="form-control" value="@Model.Phone" />

    <label asp-for="Email" class="control-label">Email</label>
    <input type="text" step="0.01" name="Email" class="form-control" value="@Model.Email" />

    <input type="submit" value="Update Inquiry" class="btn btn-primary" />
}

InquiryApp/Views/Inquiry/ViewInquiry.cshtml
@using BusinessSolution
@model InquiryModel

<!-- Display details of a single inquiry -->
<h3>@Model.Name</h3>

<table class="table">
    <tr>
        <th>Inquiry ID</th>
        <th>Date</th>
        <th>Phone</th>
        <th>Email</th>
    </tr>
    <tr>
        <td>@Model.Inquiry_ID</td>
        <td>@Model.Date.ToString("MM/dd/yyyy")</td>
        <td>@Model.Phone</td>
        <td>@Model.Email</td>
    </tr>
</table>

<div style="display: block">
    <a href="/Inquiry/UpdateInquiry/@Model.Inquiry_ID">Update this inquiry</a>
</div>

<div style="display: block">
    @using (Html.BeginForm("DeleteInquiry", "Inquiry", "Post"))
    {
        <input type="hidden" asp-for="Inquiry_ID" value="@Model.Inquiry_ID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this inquiry" />
    }
</div>